config/routes.rb
Rails.application.routes.draw do
  resources :user_forms

  root 'user_forms#index'
  

end

app/models/concerns/user_profile_validations.rb
require 'active_support/concern'

module UserProfileValidations
  extend ActiveSupport::Concern

  included do

    validates_format_of :postal_code,
                        with: /\d{2}-\d{3}/,
                        message: "should be 12-345"

    


  end
    
  end

app/models/concerns/user_validations.rb
require 'active_support/concern'

module UserValidations
  extend ActiveSupport::Concern

  included do
    validates :login, :presence => true
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_one :user_profile
  
  include UserValidations
  
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  
  belongs_to :user

  include UserProfileValidations
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  
  def new
    @user_form = UserForm.new
  end
  
  def create 
    @user_form = UserForm.new
    if @user_form.submit(user_forms_params)
      flash[:notice] = 'SUCCESS'
      redirect_to '/'
    else
      flash[:error] = "FAILURE"
      render :new
    end
  end

  private

  def user_forms_params
    params.require(:user_form).
      permit(:login, :email, :city,
        :postal_code, :street, :display_name, :weather)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormObject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_forms/index.html.erb
HI

<%= link_to 'new',new_user_form_path %>

app/views/user_forms/new.html.erb
<%= simple_form_for @user_form do |f| %>
  <%= f.input :weather %>
  <%= f.input :login %>
  <%= f.input :postal_code %>
  <%= f.input :email %>


  <%= f.submit %>

 <% end %>